spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_shop_db
    username: postgres
    password: 0211
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.web: "debug"
    org.hibernate: "error"
  output:
    ansi:
      enabled: always
jwt:
  token:
    secret: ZG9uaWtJbnRlcm5Qcm9qZWN0IDI2LjAyLjIwMjQ
    validity: 60000